FROM nginx:alpine

WORKDIR /usr/share/nginx/html

# Remove default nginx static assets
RUN rm -rf ./*

# Copy static assets and dist files
COPY public/dist ./dist
COPY public/index.html .
COPY public/favicon.ico .

# Copy nginx configuration
COPY docker/dev/nginx.dev.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"] 