FROM nginx:alpine

WORKDIR /usr/share/nginx/html

# Remove default nginx static assets
RUN rm -rf ./*

# Copy static assets and dist files
COPY public/dist ./dist
COPY public/index.html .
COPY public/favicon.ico .

# Copy nginx configuration
COPY docker/prod/nginx.conf /etc/nginx/conf.d/default.conf

# SSL directory
RUN mkdir -p /etc/nginx/ssl

# Create directory for certbot
RUN mkdir -p /var/www/certbot

# Expose ports
EXPOSE 80
EXPOSE 443

# Start Nginx
CMD ["nginx", "-g", "daemon off;"] 