FROM nginx:alpine

# Copy static files
COPY public /usr/share/nginx/html

# Copy SSL configuration
COPY docker/prod/nginx.conf /etc/nginx/conf.d/default.conf

# Create directory for certbot
RUN mkdir -p /var/www/certbot

# Expose ports
EXPOSE 80
EXPOSE 443

# Start Nginx
CMD ["nginx", "-g", "daemon off;"] 